#!/bin/bash

# todo program
# Manage a simple todo list in the terminal
# John Craffey
# 8-8-2019

# Create the todo list file if not created yet
if ! test -e "todo.txt"; then
	echo "### todo list ###
	" > todo.txt
fi

# Check argument validity
arg1=$1
if [[ $arg1 != "add" && $arg1 != "list" && $arg1 != "complete" \
		&& $arg1 != "help" && $arg1 != "remove" ]]; then
	echo -e "Input error. Try running\n 	'todo help'"
fi

# If working with a task, put task name in a variable
if [[ $arg1 == "add" || $arg1 == "complete" || $arg1 == "remove" ]]; then
	task=$2
fi

# Do something based on what first argument is
case "${arg1}" in
	# Add a task
	"add" )
		# Append the task to the todo list
		echo -e "Task: $task\nStatus: Incomplete\n" >> todo.txt
		# Output response
		echo -e "Task added.\nTask: $task\nStatus: Incomplete\n\n"
		echo "run \"todo complete '$task'\" to mark as complete.";;

	# List all tasks
	"list" )
		cat todo.txt;;

	# Complete a task
	"complete" )
		# Edit the file in place to change status to complete
		sed -i "/$task/!b;n;cStatus: Complete" todo.txt 
		# Output response
		echo -e "Task completed.\nTask: $task\nStatus: Complete";;

	# Remove a task
	"remove" )
		# Remove the lines from todo list
		sed -i "/$task/,+2 d" todo.txt
		# Output response
		echo "$task has been removed.";;

	# List options
	"help" )
		echo
		echo "Welcome to todo!"
		echo "Valid first arguments include:"
		echo -e "	add\n	complete\n	remove\n	list\n	help"
		echo
		echo "To list all tasks use the format:"
		echo "\"todo list\""
		echo
		echo "To add or edit a task task use the format:"
		echo "\"todo <command> '<task name>'\""
		echo ;;
esac

